import { Principal } from "@dfinity/principal";
import * as token from "../../dfx_generated/token/token.did.js";
import * as provision from "../../dfx_generated/provision/provision.did.js";

export const SampleCollectionInit = {
  supply_cap: 5n,
  price: 100000n,
  treasury: Principal.anonymous(),
  token: Principal.anonymous(),
  index: Principal.anonymous(),
  asset_canister: Principal.anonymous(),
  collection_owner: Principal.anonymous(),
  weight: 0,
  drive_type: "",
  brochure_url: "",
  purchase_price: 0n,
  documents: [],
  images: [],
  cargo: 0,
  displays: "",
  seating: "",
  logo: "",
  name: "",
  overall_height: 0,
  description: "",
  overall_width: 0,
  track_front: 0,
  ground_clearance: 0,
  key_features: [],
  range_per_charge: 0,
  track_rear: 0,
  acceleration: "",
  charging_speed: "",
  wheels: 0,
  battery: "",
  overall_length: 0,
  symbol: "",
};

export const SampleCollectionUpdate = {
  weight: [],
  drive_type: [],
  brochure_url: [],
  purchase_price: [],
  token: [],
  index: [],
  documents: [],
  images: [],
  supply_cap: [],
  cargo: [],
  displays: [],
  seating: [],
  logo: [],
  name: [],
  overall_height: [],
  description: [],
  overall_width: [],
  track_front: [],
  asset_canister: [],
  ground_clearance: [],
  key_features: [],
  range_per_charge: [],
  track_rear: [],
  acceleration: [],
  charging_speed: [],
  wheels: [],
  price: [],
  battery: [],
  overall_length: [],
  symbol: [],
  treasury: [],
} as Parameters<token._SERVICE["update_metadata"]>[0];

export const SampleCollectionRequest = {
  supply_cap: 5n,
  price: 100000n,
  treasury: Principal.anonymous(),
  token: Principal.anonymous(),
  index: Principal.anonymous(),

  weight: 0,
  drive_type: "",
  brochure_url: "",
  purchase_price: 0n,
  documents: [],
  images: [],
  cargo: 0,
  displays: "",
  seating: "",
  logo: "",
  name: "",
  overall_height: 0,
  description: "",
  overall_width: 0,
  track_front: 0,
  ground_clearance: 0,
  key_features: [],
  range_per_charge: 0,
  track_rear: 0,
  acceleration: "",
  charging_speed: "",
  wheels: 0,
  battery: "",
  overall_length: 0,
  symbol: "",
} as Parameters<provision._SERVICE["add_collection_request"]>[0];
