name: Deploy Canisters
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "scripts/**"
      - ".github/workflows/deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-canisters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.20.0"

      - name: Confirm successful installation
        run: dfx --version

      - name: Setup env to deploy
        run: |
          touch actions_identity.pem
          echo "${{ secrets.FUEL_DAO_SNS_CONTROLLER_ADMIN_PRIVATE_KEY }}" > actions_identity.pem
          dfx identity import --storage-mode plaintext actions actions_identity.pem
          dfx identity use actions

      - name: Install npm packages
        run: yarn install --frozen-lockfile

      - name: Get Asset Canister WASM
        run: yarn wasm:setup

      - name: Start DFX Server
        run: dfx start --background
      
      - name: Create canisters
        run: dfx canister create --all

      - name: Generate client
        run: dfx generate

      - name: Deploy infrastructure
        run: DFX_NETWORK=ic IDENTITY_PEM_FILE=./actions_identity.pem npx ts-node ./scripts/deploy.ts

      - name: Upgrade token canisters
        run: dfx canister call provision upgrade_token_canisters --ic

