name: Test canisters on PRs and push to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version
      
      - name: Install npm packages
        run: yarn install --frozen-lockfile

      - name: Start DFX Server
        run: dfx start --background
      
      - name: Create canisters
        run: dfx canister create --all

      - name: Get Asset Canister WASM
        run: yarn wasm:setup

      - name: Build canister
        run: yarn build
      
      - name: Generate client
        run: dfx generate

      - name: Run test
        run: yarn test